FROM python:3.11.9


ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_ENV=production

WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
 && pip install --no-cache-dir gunicorn 

# 3. 전체 프로젝트 코드 복사
COPY . .

# 4. AWS 배포 및 운영을 위한 정적 파일(CSS/JS) 모으기
RUN python manage.py collectstatic --no-input

# 5. 8000번 포트 노출
EXPOSE 8000

# 6. gunicorn을 통한 운영 서버 실행 (마이그레이션 후 실행)
CMD ["sh", "-c", "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"]