# Generated by Django 5.2.12 on 2026-03-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_hashtag_post_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='Hashtag',
            new_name='hashtag',
        ),
    ]
