# Generated by Django 5.2.12 on 2026-03-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contene',
            new_name='content',
        ),
    ]
